language: ruby
rvm:
- 2.3.3
before_script:
- bundle exec rake db:create --all
- bundle exec rake db:migrate
script:
- bundle exec rake spec
services:
- postgresql
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: BsT4kEe6RAGMcoQqjWocEEfHMBEkgl8fqTYzH/zRI7eaNy4YQYhtKpYmAGk19tQlXnlDmr/FeGPmylAan7utmV4BSRIuJ1JRBKeq4xg1WH+SsUz58n4+hwFOYnUYFXJDxPuAGKMqgIS9IcUqt0WUSgEjzYdcZa7LCsgi0VfYG7O98PNWUgU8Py+CeNQMoi7RjPPj0G0e3dhAFkO1lINW6wI/ph6ktZA0I7xv9VEZPdomdozt9snLZD2/U8TxwaEI2waaYE4kG2Zvi/Oh7UoafIQz3oYU++AcFdPJcbNBwR5CmH7NvhOAw0Zb2V9Uk1g4NPuYNsS87Ym4qaS2tXVRpfAmlx+Hg41gk0ltBp2QCf3X2aEb0AfNditlmh4K9ZnYPA6XWN3LtC84V0QJNGXse3Uz1uke4a8px210jLZyb0XmaoVG9Y3xZAR6QCdVrg84gl9h1/dn6SyDyoWgF24ADt+Rn5WZqTWSW4z6Fc/no5f/h3h1tep233B/nM4mPliLrdABGhMWKH1HC4UKa7kyrnYlbJ8y3xEhJFssu0F/xpoAh2PLrmilUzOkem9OfmDbKjjHg+DCYlxJYZCNvxnEPEyH6uHl0tuO/EfgUgG1OQo7wn97KiSi8J39FO4VJGFZWPBPwSmpG4rKJaAZsOgamd6I5CrXTqi7nEBd7eW/sKY=
  app: rails-api-skeleton
  on:
    repo: barmic12/rails-api-skeleton