language: ruby
rvm:
- 2.3.3
before_script:
- bundle exec rake db:create --all
- bundle exec rake db:migrate
script:
- bundle exec rake spec
services:
- postgresql
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: OgoWQRuWn3sdFOwOsvysIgGbhmnOMnznvXRwllpKA+UmPFmRFRMErZVLncJvnTImcf2dURmINYgJ2skFzrjubbksw9/CbCm+mtOO6LMhE+6lDGDEMyZFEVr2S0M6BQOprF4rI6W1rGWYthu5bWoA5bhFbL7CrSAC4oGyGRl7mWFO5jeuF8+Jdp3N+AhCSFEjuZugQbmDao4VFDCP2Id6NFzD9oiFn0c6pnz8qaIrbk+spvzwEdQQuzAtYpQ+KsluT7Wb4piA6g+QRRNEc8wBTRerd8hj2NQAxGtUBdneQQCGGDPEhRxZZuGLYAJcuexEEpLM4L4IhxCxCqn0Djjmo0p+PK/uQgqlJByOzdw71U8PT/xnNAVpOh3WLzNqU77xdFC8J830JD8FovVBA6WAq6Iesq5HugWgFGuyWbucLcEhyZoyROd+NrD9cT7J2DEryO70vLSHVME8QRE2MfBThJUUDrq95Xr+HfrAiJN99lLMXi8+U6CWZguWEOynlohDdMdI5KQJqwccohljYaD8NkLBoWT0RmRJY4vIbGv9cFLyJhDizbEL/XGlEMKuXUxM0CXvBWt5zCNI9VwRbtzNdtX4SqOwDb6uuPa5foO632kftqpCa6XBlOhmuD11PlphAGnSoBi0T719/n4rmmoqpubKRGo1BSsAP0VovW9cqJs=
