language: ruby
rvm:
- 2.3.3
before_script:
- bundle exec rake db:create --all
- bundle exec rake db:migrate
script:
- bundle exec rake spec
services:
- postgresql
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: pzTd3ND6o41ydM9/NIa2DAhsRpq5zodJczEwXZx20E1IFeXFH5cZGr/vRnLvUMoBfL0rtbWK0lE3DX3Fowpudof+qBlVmc9xiYl45JL2hLRlmXHKyY60AwX8feptrn4jNH1xPHqwGD20AZ4cdzU/PXg6Jxbb8DqOeohjZ3rgdFXqOCvv1M7n3lBXtCIUrg1UvJSTXjYjXs43nVLspnR6W6uFoNb+CPs9cEMwIMq10O6Ha+KNPTZkrylGBxRmHrpUwEUbG2pxxP17lxad9LbR1Js9z3VQkbmbOTbPz+Ex0TmOa8jDrF45xnLOxk0xZwAiOY9fxb0yl3FvYx6OzxROm31jkyuDhIUAOtu37VmJ2jsYGanUj9AiurBroMP6y3kaCXDXWQQo/PUUHqZ2SEYUSZCjAgYwYNccvHgCVoI6K77SZZrYZdBIafHbeMJlitGmLdlhCQsUg9p9JyA+FuoCRb1+uJfX3Avscs129LIsEpqTQHzjzQzA8V4bm7iST7uN7qVtp8UlxbqxC9oygqP2C7LQlh89bAs1RTm0S7yNzneT8+dTLKMM9so3R5LQC1o5cZoCPkCzv+97LwNTBXSin0SDaH8Wf5W9jQwNooQ9u9swWpSjaR40NZBbK6EyVxWKWfkxP6R0fOdxhIiQUhaAU1enRk9eCWjY3T14oWf2qns=
  app: rails-api-skeleton
  on:
    repo: barmic12/rails-api-skeleton