language: ruby
rvm:
- 2.3.3
before_script:
- bundle exec rake db:create --all
- bundle exec rake db:migrate
script:
- bundle exec rake spec
services:
- postgresql
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: apAcTeT+Wu/iv1s+UccJf9V2AokbECfJBdindq6RkMqU5mysdShaNI0i9Ig2lqDTgqwlr9TnLFMjwpyh8KOPylGthKfns+tdJVgrsbZrI6P1GLMiu/VWnRmSFKjApmSLgZ5taENF4hjZvXeYkXi5Ia+8QEMy8gj2eWfeYVvf3hT2cbQ2iNHx0ooUQK7dUf3AdLNFxjaL8NTd+2KRsUQNIi+Ar6XOo8ja/F+QkDFdXH0GLRARAUEiDyPVoGLkuyNYzmsLw6oRiLFNjTw2shOvuWB9DBZpv9S8E+8mq4nAkhJ383G233JZjIzmWj5AQ//NYBgeWnzWJ0OKef2syH2BpWwSN1p2cagSGaZRqFEL2Nb/KHP/B9Q69XbuXabf8oifHrWzyctqR0MXjyNQYM1vtkGN8rylCQqFc21qkXSipeBjZzPbFw5p3Md6TQsDy8c+6rPqzGmmRu4Lu3mFEdoknNBHua78lWUWcgGjeLmvosXRfxZrWeH0R+rmQ9WLf+cb3osilG6sNMxT90lHzSjBkZJjdEq3l/Xlfavqy+JrVCVOosgoaFaOjcSjm3PWU6c8776guWb2FBr/4RZ4r4Ih3JEsL6N0hZMrK/kYBDw3Jvz47CdggajGOLpy9Bf4MAe1KEOpb263Yp32wcQN+tpKWft9VzFORDTOOVWqOFbHuCE=
  app: rails-api-skeleton
  on:
    repo: barmic12/rails-api-skeleton
