language: ruby
rvm:
- 2.3.3
before_script:
- bundle exec rake db:create --all
- bundle exec rake db:migrate
script:
- bundle exec rake spec
services:
- postgresql
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: HytPPshXQjYvZOC3epy9kbdKh1uCaf9AfmdoL53yj6ZCj7oO3OYQBNHqFsIEStyvXuZ07gdPDOtuC+uqzf1OUb1ZxyyNFXDsjv9gL+9F4QmUx+SDPYLFPPnG806ZBM/UPN1yLZjytYjf8Mk8FFd3KzIU6wyDabmckkdLULJCA+6oE22FX66R5ZYhIAQ3sjPTbK757XRWh68t3dAywd1GgeUEdDy0wK/cNZAvURRIyqHkmV9iuQ+vHkKuyQKntuL2Tgc8yy9UzmBI7DR9IOfbxQ1XyITezYHc3T4sgzOCBGTIPYfMB0KYKtX/DW3PVbsZENS+lkqAxIunJJaNw/VF/GfsbDGoyKLh8dprq1yMYM/n39RNvoZVx7AJ2/HZ+zjPHJqQdIsQoyUg9uv0+mfyxyZmjrjQ2aVSJvU9lyyZ1hVqwrZ+EWspNrwQw8T79hXCpL5iHOjTKYChLSZ+gEUpk3Ql3IZ0+xz86Fzn8KHaa4VmSS50XWKJ1setE4itW1eaGNoSBLfcLO7OnEw9InUq8ggaJ85Zg+BHX9qgwzv7Z17fIXxRrs1ry2ygSUR9uo/ysWD7hkt9toy3xSOe3hGOpWcGPSFpa2FG6+K0r3cYwFerMM5h8/dVuhax6oBh5soX9v/MOwn3NMsLWHkgpWgGbloWcvtwJku5Gb7X8VqDJoI=
    on: master