language: ruby
rvm:
- 2.3.3
before_script:
- bundle exec rake db:create --all
- bundle exec rake db:migrate
script:
- bundle exec rake spec
services:
- postgresql
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: YZl4W8dq+T6VZCmkRpHc5QUCqVgZ4+2ZQZRme1yko+ABhxfcEomUKLAbtRlGsURfOg14Bas6jHntXr1QpLtEPLh6ISwT5c7NbV7uRGivO4bhX0A2Gvt17Heqkn+nXN+EPPSg/L0c75Y/BxQNXj/ZojC+6tEaSaHiS3pCtH6L3TiCynECbdXVFZ4PInDDR9p7896DWNbmRtIfjK4thsFMobu/gMMrWrabyko/7l84VkFtb6gyCeuPJayZ8DD0NaiMJaxj1KYDT9EfqN3j6wrE/Q9ED3PHK6b4Twu34yBLxrjyJcFxkBTrM4vpDAppO5tSVJlc98h0fhHeQ5B0oHgww/OCP8A4IcWek8ArNdB3r2p7dxrGJfdtPsg0gr8JAHpXTsAnhDKfFbvYHeLurLxqOBjo1akq+0ChfKdFKwAxkhfSrEJi7LNQh1MZDiWSGHoXvwWQ+l0YtBEs85qmAqr96N+Kom+ecjq+4Z31S1EU9Yk8jLT7wcRNY6YsEULrqTupZfiweuf8QNiVgR/5i1UYsfwkJAeZ9Dob1PXtAiq18qJLMExDrt4WyECm23k0Ep+WSnqd8nM+PCY8RYnhvNg3KanCEoc37LNb0g1vpJiHbEY8zAN542CcPPa+cOZzen8Yvxk+Uvp5QB/XIUYQlmQhyOk5B3KIW1BE4D9SEZrkjVs=
  app: rails-api-skeleton
  on:
    repo: barmic12/rails-api-skeleton